# Generated by Django 5.2.6 on 2026-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activeinfo_pendinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeinfo',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='activeinfo',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='pendinginfo',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='activeinfo',
            name='approved_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='activeinfo',
            name='approved_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeinfo',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activeinfo',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='activeinfo',
            name='submitted_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeinfo',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pendinginfo',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pendinginfo',
            name='submitted_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinginfo',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
